### ISSUE TITLE
Is it possible to add option to choose sources?

### ISSUE THREAD

**Issue by erotavlas** [Georgetown-IR-Lab/QuickUMLS#49]
I was wondering if it is possible to add an additional option to specify the vocabulary sources when initializing the QuickUMLS object (i.e. RXNORM, NCI, etc) similar to the option for semantic types (accepted_semtypes)

And also to expose this information in the output.

**Comment by soldni** [comment]
Hi,

Unfortunately this is not currently this is not possible because information on which subset(s) a concept comes from is currently not stored. For the moment, I'd recommend creating different installations of UMLS you can load a QuickUMLS matcher from. 

Feel free to cut a CR for this in case you want to support this function!

Thanks,
Luca
